### ISSUE TITLE
[Feature Request] Vanilla Creative menu

### ISSUE THREAD

**Issue by superdboy4** [RockinChaos/FakeCreative#3]
Thanks for making this amazing plugin RockinChaos, its exactly what i was looking for.

I do have a request, if possible however. 
Instead of your costum creative menu, is it possible to just use the vanilla one used by minecraft itself? (when you press e)
 Basically just Creative mode but with survival is what i'm looking for. 

now i think the reason that you used a costum menu is to combat the nbt item spawning and stuff. ( i think)
But i already got around that another way.

Like a toggle in the config, Costum menu true/false or something like that.

Thanks for reading this suggestion! ;)
- superdboy4

**Comment by RockinChaos** [comment]
Hi, so actually, the main reason I did a custom menu instead of the regular menu is because it's simply not possible to utilize. We as developers get no control over it as it is entirely client-sided. Hense why there are a lot of exploits with the creative menu is because of its nature of being client-sided. 

So, unfortunately, this isn't something I can implement as there is no way to even pull up the menu, even if I forced the player to use the default creative mode designed by Mojang, we just can't interact or forcibly pull up that creative menu.

That is why the custom one I designed exists for the most part. If you feel like there are some improvements that can be made to the menu I designed feel free to drop some suggestions. I do have a small re-work I am working on to make it a bit more seamless so look forward to that coming soon.
